### ISSUE TITLE
Broken build with the mbed-drivers (~0.6.4)

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/example-mbedos-blinky#6]
Need to investigate why this latest PinDef change affected old mbed drivers.

The error:
```
example-mbedos-blinky/yotta_modules/mbed-hal-ksdk-mcu/mbed-hal-ksdk-mcu/objects.h:22:22: fatal error: PinNames.h: No such file or directory
 #include "PinNames.h"
```

list:
```
example-mbedos-blinky 0.0.0
|_ mbed-drivers 0.6.9
| |_ mbed-hal 0.6.4 yotta_modules\mbed-hal
| | |_ mbed-drivers *
| | \_ mbed-hal-freescale 0.5.2 yotta_modules\mbed-hal-freescale
| |   \_ mbed-hal-ksdk-mcu 0.5.7 yotta_modules\mbed-hal-ksdk-mcu
| |     |_ mbed-hal *
| |     |_ uvisor-lib >=0.7.0,<0.8.0
| |     \_ mbed-hal-k64f 0.3.6 yotta_modules\mbed-hal-k64f
| |       |_ mbed-hal *
| |       |_ uvisor-lib >=0.7.0,<0.8.0
| |       \_ mbed-hal-frdm-k64f 0.4.5 yotta_modules\mbed-hal-frdm-k64f
| |         \_ mbed-hal >=0.6.0,<0.7.0
| |_ cmsis-core 0.2.7 yotta_modules\cmsis-core
| | \_ cmsis-core-freescale 0.1.4 yotta_modules\cmsis-core-freescale
| |   \_ cmsis-core-k64f 0.1.5 yotta_modules\cmsis-core-k64f
| |     \_ cmsis-core >=0.2.0,<0.3.0
| |_ ualloc 0.0.10 yotta_modules\ualloc
| | |_ dlmalloc 0.0.6 yotta_modules\dlmalloc
| | |_ mbed-drivers >=0.1.1
| | \_ cmsis-core *
| |_ minar 0.6.7 yotta_modules\minar
| | |_ compiler-polyfill 1.0.4 yotta_modules\compiler-polyfill
| | |_ minar-platform 0.3.4 yotta_modules\minar-platform
| | | |_ minar-platform-mbed 0.1.5 yotta_modules\minar-platform-mbed
| | | | |_ cmsis-core >=0.2.0,<0.3.0
| | | | |_ mbed-hal >=0.6.0,<0.7.0
| | | | \_ minar *
| | | \_ cmsis-core >=0.2.0,<0.3.0
| | |_ mbed-drivers >=0.7.0,<0.8.0
| | \_ core-util >=0.0.6,<0.1.0
| \_ core-util 0.0.16 yotta_modules\core-util
|   |_ cmsis-core >=0.2.2,<0.3.0
|   |_ ualloc >=0.0.4,<0.1.0
|   \_ mbed-drivers *
\_ uvisor-lib 0.7.25
  \_ mbed-drivers *
```

**Comment by 0xc0170** [comment]
For frdm-k64f-gcc, this version breaks the build - https://github.com/ARMmbed/mbed-hal-frdm-k64f/commit/1947141e0bd342a38eec5ab68acea1708319551f

To fix it, we can revert that breaking change, release a new patch, then resend the change and do a proper new minor version to match upper layers changes.

**Comment by 0xc0170** [comment]
mbed-hal-frdm-k64f 0.4.6 fixes this
